version: "3"
services:
  # tag::messaging[]
  messaging:
    image: "rabbitmq:3.8.8-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
  # end::messaging[]

  # tag::DB[]
  db:
    build: ./DB
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # tag::DB[]

  # tag::adminer[]
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


  # tag::front_end[]
  front_end:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
  # end::front_end[]

  # tag::back_end[]
  back-end:
    build: ./backend
  # end::back_end[]
volumes:
  data-volume:
