version: "3"
services:
  # tag::messaging[]
  messaging:
    image: "rabbitmq:3.8.8-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
  # end::messaging[]
  # tag::adminer[]
