version: "3"
services:
  # tag::messaging[]
  messaging:
    image: "rabbitmq:3.8.8-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
  # end::messaging[]

  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

  # tag::front_end[]
  front_end:
    build: ./frontend
    ports:
      - 5000:5000
  # end::front_end[]

  # tag::back_end[]
  back-end:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
  # end::back_end[]
volumes:
  db-data:
