version: "3"
services:
  # tag::messaging[]
  messaging:
    image: "rabbitmq:3.8.8-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
  # end::messaging[]

  db:
    build: ./DB
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # tag::adminer[]
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  data-volume:
