version: "3"
services:
  # tag::messaging[]
  messaging:
    image: "rabbitmq:3.8.8-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
  # end::messaging[]
  # tag::adminer[]
  # end::adminer[]
  # tag::front_end[]
  front_end:
      build: ./frontend
      command: npm start
      ports:
          - 3000:3000
      environment:
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      volumes:
        - "./frontend:/usr/app/"
    # end::front_end[]
